version: '3.1'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile_bot
    ports:
      - "5000:5000"

  model:
    build: 
      context: .
      dockerfile: Dockerfile_model
    ports:
      - "6000:6000"