# Используем официальный образ Python
FROM python:3.8

# Устанавливаем рабочую директорию
WORKDIR /usr/src/bot

# Устанавливаем зависимости
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Копируем файлы бота
COPY . .

# Указываем команду для запуска приложения
CMD [ "python", "./Tinkoff_Sirius_bot.py" ]